name: Build with Script (Manual Only)

on:
  # Disabled automatic triggers - only manual dispatch allowed
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image with script
      env:
        CI: true
      run: |
        chmod +x scripts/build_image.sh
        bash scripts/build_image.sh

    - name: Test image
      run: |
        docker run --rm zkwasm:latest echo "Image test successful"

    - name: Tag and push image
      if: github.event_name != 'pull_request'
      run: |
        # Generate 7-character short SHA
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        
        # Tag the image with your Docker Hub username
        docker tag zkwasm:latest ${{ secrets.DOCKERHUB_USERNAME }}/zkwasm:latest
        docker tag zkwasm:latest ${{ secrets.DOCKERHUB_USERNAME }}/zkwasm:${SHORT_SHA}
        
        # Push both tags
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/zkwasm:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/zkwasm:${SHORT_SHA} 