name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: zkwasm

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      run: |
        # Generate tags
        TAGS=""
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
          TAGS="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:main"
        elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/master" ]]; then
          TAGS="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:master"
        elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" =~ ^refs/tags/ ]]; then
          TAG_NAME=${GITHUB_REF#refs/tags/}
          TAGS="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG_NAME},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
        else
          TAGS="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.number }}"
        fi
        
        # Add commit SHA tag
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        TAGS="${TAGS},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:sha-${SHORT_SHA}"
        
        echo "tags=${TAGS}" >> $GITHUB_OUTPUT
        echo "Generated tags: ${TAGS}"

    - name: Build Docker image
      env:
        DOCKER_BUILDKIT: 0
      run: |
        echo "Building Docker image with DOCKER_BUILDKIT=0..."
        docker build --rm --network=host -t ${{ env.IMAGE_NAME }}:latest .
        
        echo "Docker build completed successfully"

    - name: Test Docker image
      run: |
        docker run --rm ${{ env.IMAGE_NAME }}:latest echo "Image test successful"

    - name: Tag and push Docker image
      if: github.event_name != 'pull_request'
      run: |
        # Split tags and push each one
        IFS=',' read -ra TAG_ARRAY <<< "${{ steps.meta.outputs.tags }}"
        for tag in "${TAG_ARRAY[@]}"; do
          echo "Tagging image as: ${tag}"
          docker tag ${{ env.IMAGE_NAME }}:latest ${tag}
          echo "Pushing: ${tag}"
          docker push ${tag}
        done
        
        echo "All images pushed successfully"

    - name: Image digest
      if: github.event_name != 'pull_request'
      run: |
        docker inspect ${{ env.IMAGE_NAME }}:latest --format='{{index .RepoDigests 0}}' || echo "No digest available for local image" 